name: Github Actions Example

on: 
  pull_request:
  push:
    branches: 
      - master
      - develop
      
jobs:
 test:
   name: Running Unit Tests
   runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install
      run: npm install
    -name: Test
     run: npm test
       
