name: Github Actions Example

on: 
  pull_request:
  push:
    branches: 
      - master
      - develop
              
jobs:
 test:
   name: Running Units Tests
   runs-on: ubuntu-latest
    
   steps:
    - uses: actions/checkout@v1
    - name: Build Code
      run: make
    - name: Nominal Run
      run: ./hello
    - uses: actions/upload-artifact@master
      with:
        name: hello artifact
        path: hello
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#        node-version: ${{ matrix.node-version }}
#     - name: Install
#       run: npm install
#     - name: Test
#       run: npm test       
